services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    image: clisp:latest
    volumes:
      - .:/var/www/html
    command: >
      sh -c "
        chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
        chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
        php-fpm
      "
    networks:
      - app-network
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  database:
    image: mariadb:latest
    env_file:
      - .env.production
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  db_data: {}
