services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    image: clisp:latest
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  database:
    image: mariadb:latest
    env_file:
      - .env.docker
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  db_data: {}
