name: Clisp Deployment

on:
  workflow_run:
    workflows:
      - Laravel Test
    types:
      - completed
    branches:
      - main

jobs:
  deploy_to_droplet:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -t -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /var/www/html/CLISP || git clone git@github.com:VincentNdegwa/CLISP.git /var/www/html/CLISP && cd /var/www/html/CLISP
          git pull origin main
          docker compose down
          docker compose up -d --build
          docker image prune -f
          EOF